### ISSUE TITLE
[FEATURE] 공고 등록/수정/삭제 구현

### ISSUE THREAD

**Issue by yeddorii** [devyuwon/dan-gam#11]
## 📋 이슈 내용
- 공고 등록/수정/삭제 등을 구현함
- :cat:**[default화면 : 공고작성Page]** :cat:  **🐧 [중요도] 상: ⭐⭐ ⭐  중: ⭐ ⭐  하: ⭐  🐧** 
  - [버튼]클릭 시 - [연동되는 페이지]

    - [뒤로가기] - [마이페이지], [공고리스트 페이지], [공고메인 페이지] (⭐⭐⭐)
    - [위치설정] - [지도설정 페이지] (⭐⭐⭐)
    - [작성완료] - [공고메인 페이지] (⭐⭐⭐)
    - [확인] - [공고작성 페이지] (⭐⭐⭐) **[화면 : 지도설정Page]**
- :panda_face:구현 기능:panda_face:

  - [일감/일꾼] 클릭 시 색상 변경 (⭐⭐)
  - [사진] 클릭 시 사용자 사진 첨부 기능 (⭐⭐⭐)
  - 지도설정 화면에서 GPS로 위치 설정  (⭐⭐⭐)

## ✔️ To-do
- [x] :one: 공고 작성/수정/삭제와 관련된 전체 디자인 목업
- [x] 2️⃣ [일감/일꾼] 클릭 시 색상 변경
- [x] 3️⃣ [사진] 클릭 시 사용자 사진 첨부 기능
- [x] 4️⃣ [위치설정] - [지도설정 페이지]
- [ ] 5️⃣ 지도설정 화면에서 GPS로 위치 설정
- [x] 6️⃣ [확인] - [공고작성 페이지] 연동
- [x] 7️⃣ [작성완료] - [공고메인 페이지]
- [x] 8️⃣ [뒤로가기] - [마이페이지], [공고리스트 페이지], [공고메인 페이지] 

## 🤔 필요 데이터
- 구글 지도 API
- 
-
