### ISSUE TITLE
[FEATURE] 공고 MainPage

### ISSUE THREAD

**Issue by yeddorii** [devyuwon/dan-gam#12]
## 📋 이슈 내용
- 공고를 작성 완료하였을 때 나오는 Main Page
- 공고 상세 내용을 확인가능
- 공고 상태 변경
- :cat:**[default화면 : 공고 Main Page]**:cat:  **🐧 [중요도] 상: ⭐⭐ ⭐  중: ⭐ ⭐  하: ⭐  🐧** 
  -  [버튼]클릭 시 - [연동되는 페이지]:cat:
     - [수정] - [공고 작성 페이지] (:star::star::star:)
     - [삭제] - [공고 리스트 페이지], [마이페이지] (:star::star::star:)
     - [뒤로가기] - [공고 리스트 페이지], [마이페이지] (:star::star::star:)

- :panda_face:구현 기능:panda_face:

  - [메뉴] 클릭 시 라디오 버튼 팝업 구현 : 액션바X, 툴바 이용 (:star::star::star:)
  - [삭제], [메뉴] 클릭 시 전체 화면 불투명하게 구현 : 액티비티 이용 (:star:)
  - [삭제]클릭 시 팝업 알림 구현 (:star::star::star:)
  - 삭제,수정 완료 후 토스트 알림 뜨게 구현 (:star::star:)

## ✔️ To-do
- [x] 1️⃣ 공고 Main page 디자인 목업
- [x] 2️⃣ [메뉴] 클릭 시 라디오 버튼 팝업 구현 : 액션바X, 툴바 이용
- [x] 3️⃣ [삭제]클릭 시 팝업 알림 구현
- [x] 4️⃣ 삭제,수정 완료 후 토스트 알림 뜨게 구현
- [ ] 5️⃣ [삭제], [메뉴] 클릭 시 전체 화면 불투명하게 구현 : 액티비티 이용
- [x] 6️⃣ [수정] - [공고 작성 페이지] 연동
- [x] 7️⃣ [삭제] - [공고 리스트 페이지], [마이페이지] 
- [x] 8️⃣ [뒤로가기] - [공고 리스트 페이지], [마이페이지]

## 🤔 필요 데이터
- 사용자 사진
- 
-
