### ISSUE TITLE
[FEATURE] Splash-Login 구현

### ISSUE THREAD

**Issue by devyuwon** [devyuwon/dan-gam#4]
## 📋 이슈 내용
- Splash Activity
- 애플리케이션 Login
  - Google OAuth를 사용한 간편 회원가입, 로그인

## ✔️ To-do
- [x] Splash 구현
- [x] Login 디자인 목업 
- [x] Google OAuth 연동
- [x] Login 상태 유지

## 🤔 필요 데이터
- 로그인 정보
- 정상 로그인 후 Main Page 이동
