### ISSUE TITLE
[FEATURE] 공고 등록 page 구현

### ISSUE THREAD

**Issue by yeddorii** [devyuwon/dan-gam#6]
## 📋 이슈 내용
-  공고 상태변경 page 구현

## ✔️ To-do
- [x] 공고 등록/수정/삭제/진행상황 디자인 목업
- [ ] 위치(gps)연동
- [ ] 공고리스트 page 연동
- [ ] my page 연동

## 🤔 필요 데이터
-  메인 페이지
-  공고 리스트 페이지
